name: CI/CD multistage pipeline
on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      -main
jobs:
  # buid stage
  setup:
    name: Setup Project
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: Cache Node Modules 
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: "${{runner.os}}-node-${{ hashFiles('**/package-lock.json')}}"
          restore-keys: |
            "${{ runner.os }}-node-}}"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
    
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: lint it properly
        uses: actions/setup-node@v4
      - name: run npm
        run: npm ci
      
  test:
    name: run tests on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs : setup
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm run lint

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Build Artifact
        id: upload-artifct
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./dist
          retention-days: 10
       
  deploy:
    name: Deploy to github
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download
        uses: actions/upload-artifact@v4
        with:
          name: build
      - name: Deploy to Github
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_Token }}
          publish_dir: ./dist
